### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by wlll123456** [NHirose/learning-language-navigation#2]
Recently, I had the pleasure of reading your paper LeLaN, and I must say it is an impressive piece of work. However, I have a few questions that I would appreciate your clarification on:
1.	In Figure 2, is it correct to understand that Metric3D and Depth360 are used to generate the 3D scene? And is the entire training pipeline for the model optimized in this 3D scene environment?
2.	Regarding the 2D data from the YouTube videos, are they only used to generate data, without directly being involved in the model training process?
3.	In Figure 3, when comparing with CoW, are you using NoMaD trained on the dataset you generated?

I look forward to your response and appreciate your time in addressing these questions.

**Comment by NHirose** [comment]
I answer for each question as follows,

1. Yes. The estimated 3D points are used to label the target object pose.
2. We use the images from the YouTube video as well as the annotated labels in our training.
3. No.

**Comment by wlll123456** [comment]
I would like to ask whether, when it comes to deploying the model onto the robot, the model architecture on the robot includes the LLM and VLM models？

**Comment by NHirose** [comment]
As shown in our paper, we have no LLM and VLM in inference. Please check our paper. The network structure is shown in the appendix.
https://arxiv.org/abs/2410.03603
