### ISSUE TITLE
Data preparation code

### ISSUE THREAD

**Issue by evgeniishch** [NHirose/learning-language-navigation#3]
Is it correct that as of now the code for data preparation pipeline (label generation) are not available?
Do you plan to release it and when?

Thank you for your work and best regards

**Comment by NHirose** [comment]
Now we are not planning to provide the code for the data annotation.

**Comment by wlll123456** [comment]
> Is it correct that as of now the code for data preparation pipeline (label generation) is not available?目前数据准备管道（标签生成）的代码不可用，这个说法正确吗？ Do you plan to release it and when?你计划发布它吗？什么时候发布？
> 
> Thank you for your work and best regards感谢您的工作，祝好

are you chinese？can i ask some question in chinese？

**Comment by NHirose** [comment]
And I am not Chinese. Please ask me in English.Thank you

**Comment by evgeniishch** [comment]
> are you chinese？can i ask some question in chinese？

No, don't speak Chinese either
