### ISSUE TITLE
Question about label consistency

### ISSUE THREAD

**Issue by evgeniishch** [NHirose/learning-language-navigation#4]
In the paper you optimize a joint objective $J = J_{pose}+J_{col}+J_{smooth}$.
However, you obtain labels for $J_{pose}$ and $J_{col}$ from different sources: $\tilde{p}_o$ from median of cropped depth point cloud, and $\overline{p}[k]$ from RFM (nomad). However these two values are geometrically connected, as $\tilde{p}_o$ is $\overline{p}[M]$ - the last point of trajectory.
My questions are:
- Is there any motivation for estimating target object pose from depth point cloud, rather than using last point of nomad generated trajectory?
- When you obtain two targets $\tilde{p}_o$ is $\overline{p}[k]$ from 2 different methods (depth and nomad respectively), could they by any chance be inconsistent? I.e. path from nomad does not lead to target point estimated from depth cloud? How does it affect the policy? Do you filter out such cases or impose consistency in any other way?

Thank you for your work and best regards

**Comment by NHirose** [comment]
When the obstacle is close to the robot, the NoMaD trajectory tries to avoid the collision (not move toward the target object). In this case, the last pose of the NoMaD trajectory is far from the target object and does not lead to learn the target reaching behavior. J_{pose} helps to learn the robotic behavior to move toward the target objects.  

The length of the NoMaD trajectory is 8. Besides, our policy is 24. Hence J_{col} affects to the first 8 steps to avoid the collision. And J_{pose} to penalize the last pose of our policy leads the policy to move toward the target object.

**Comment by evgeniishch** [comment]
> The length of the NoMaD trajectory is 8. Besides, our policy is 24. Hence J_{col} affects to the first 8 steps to avoid the collision. 

In this case what serves as label for the remaining $24 - 8 = 16$ points of the policy?

**Comment by NHirose** [comment]
The last point is supervised by the estimated target object pose. We assume that J_smooth can smoothly connect between the first 8 points supervised by NoMaD actions and the last point by the estimated target object pose.

**Comment by evgeniishch** [comment]
Thank you!
