### ISSUE TITLE
Question on target pose estimation

### ISSUE THREAD

**Issue by evgeniishch** [NHirose/learning-language-navigation#5]
Thank you for your amazing work.

In the paper you write

> For the pose estimation, we use an approach similar to
CoW [34] where we approximate the depth of the scene using Metric3D [22] for the narrow FOV
camera image and Depth360 [21] for the wide FOV camera image and project the result into estimated point clouds. By masking the estimated point clouds with masks from Segment Anything [52]
and taking the median values, we can obtain the 3D pose corresponding to an object for which we
have matching language instructions from the VLM and LLM filtering.

In case of YouTube unlabeled data, how do you solve the problem of unknown camera intrinsics/extrinsics, needed to project depth to point clouds? Do you assume some default values?

Thank you

**Comment by NHirose** [comment]
Yes. We use the default camera intrinsic parameters in the case of YouTube data. But we may be able to estimate it from the video. (we did not try it)

For the fisheye camera, we use the Depth360, which can learn and estimate the camera intrinsic parameters. Thank you.
