### ISSUE TITLE
About data preparation

### ISSUE THREAD

**Issue by K0uya** [NHirose/learning-language-navigation#6]
Hi! Thank you for your great work and publishing the code!

I would like to run train.py. However, I got the error below.
How may I prepare the folder and the file?

Thank you!

```bash
Using cuda devices: 0
go_stanford4 train flame num 33993
Traceback (most recent call last):
  File "train.py", line 565, in <module>
    main(config)
  File "train.py", line 103, in main
    dataset = LeLaN_Dataset(
  File "./train/vint_train/data/lelan_dataset.py", line 101, in __init__
    self._build_caches_front()
  File "./train/vint_train/data/lelan_dataset.py", line 132, in _build_caches_front
    with lmdb.open(cache_filename, map_size=2**40) as image_cache:
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/lelan_gs4/train/dataset_go_stanford4_train.lmdb'
```

**Comment by NHirose** [comment]
Before running "train.py", you need to download the dataset and do some processes. Please follow our instruction in readme file!
But I noticed that we need to change the directory name. After finishing the pre-process for the dataset, please change the dataset directory name "dataset_LeLaN" --> "dataset".

After that, you can run "train.py" and our code makes the files such as "dataset_go_stanford4_train.lmdb" before training only at the first trial. From the next training, our code skips to make them. Please let me know if you can not solve the issue.

**Comment by K0uya** [comment]
The training code worked successfully after I created directories such as "./dataset/lelan_gs4/train".
Thank you for your reply!
